# Generated by Django 4.2.7 on 2025-12-16 14:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('image_with_caption', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('caption', wagtail.blocks.CharBlock(label='Подпись', required=False))])), ('youtube', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock(label='URL видео YouTube')), ('caption', wagtail.blocks.CharBlock(label='Подпись', required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Встроенный контент')), ('heading', wagtail.blocks.CharBlock(icon='title', label='Заголовок')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Страница контактов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('image_with_caption', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('caption', wagtail.blocks.CharBlock(label='Подпись', required=False))])), ('youtube', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock(label='URL видео YouTube')), ('caption', wagtail.blocks.CharBlock(label='Подпись', required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Встроенный контент')), ('heading', wagtail.blocks.CharBlock(icon='title', label='Заголовок')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HotelPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Параграф')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('image_with_caption', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('caption', wagtail.blocks.CharBlock(label='Подпись', required=False))])), ('youtube', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock(label='URL видео YouTube')), ('caption', wagtail.blocks.CharBlock(label='Подпись', required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Встроенный контент')), ('heading', wagtail.blocks.CharBlock(icon='title', label='Заголовок')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, use_json_field=True, verbose_name='Контент')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='hotels.hotel', verbose_name='Гостиница')),
            ],
            options={
                'verbose_name': 'Страница гостиницы',
            },
            bases=('wagtailcore.page',),
        ),
    ]
